### ISSUE TITLE
Define utility function

### ISSUE THREAD

**Issue by mylenevdmaas** [SesswireD/ABM1#12]
We need to build a proper utility function that takes into account the velocity and direction and prefers a direct way when closer to the goal.

**Comment by SesswireD** [comment]
Yeah I agree. I think it is best / easiest to ask help from the professor. He seems good at mathematics

**Comment by SesswireD** [comment]
Prof said we could use Cobb Douglas to produce a balance between distance and preference. We need to have the weights be coupled with distance. Will close this issue for now, since we won't pursue this idea.

**Comment by SesswireD** [comment]
Prof said we could use Cobb Douglas to produce a balance between distance and preference. We need to have the weights be coupled with distance. Will close this issue for now, since we won't pursue this idea.
