### ISSUE TITLE
Network exctraction from image

### ISSUE THREAD

**Issue by SesswireD** [SesswireD/ABM1#3]
Exctract a network from the resulting trail image for analysis. Use NEFI

**Comment by mylenevdmaas** [comment]
https://mesa-geo.readthedocs.io/en/latest/apis/raster_layers.html#mesa_geo.raster_layers.RasterLayer.to_image
inbuild function to export grid as image, maybe usefull for us

**Comment by annecvdw** [comment]
I have working NEFI on my computer and I am able to extract a network into a txt file
