### ISSUE TITLE
get_cells_in_direction() allows duplicates

### ISSUE THREAD

**Issue by SesswireD** [SesswireD/ABM1#8]
Currently this function allows for the same cell being added multiple times. This results in the 'passed count' to be incremented more per step than is allowed. Remove duplicates from the cells list.

**Comment by mylenevdmaas** [comment]
I think it is fixed in the code by using set(cells) after calling that function but I agree that it should be in the get_cells_in_direction() function itself

**Comment by SesswireD** [comment]
Nik also argued that it is a feature and not a bug. If you have more samples in a given cell, meaning that it is returned as duplicates in the list, than you pass over this cell for a longer distance with respect to others. That cell should then be weighed more heavily.
