### ISSUE TITLE
IndexError occurs randomly

### ISSUE THREAD

**Issue by SesswireD** [SesswireD/ABM1#9]
Sometimes (not always) an index error occurs when trying to access individual cells on the raster_layer by indexing.
I found the error to occur at:

self.model.space.raster_layer[cell[0]][cell[1]]

sometimes it occurs when calling .passed() from the above line
sometimes it occurs when calling .agents_total from the above line

Not sure why this happens

**Comment by mylenevdmaas** [comment]
I think it happens because we did not set a limit on agents leaving the raster. So they have a certain speed and direction, then the new coordinates are computed, but in some rare cases these coordinates are outside the defined raster and so there is no cell with these indices

**Comment by SesswireD** [comment]
I changed the initialization of locations such that they are away from the border
